services:
  - type: web
    name: plaxeron
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
